apiVersion: v1
kind: ReplicationController
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: lukereimer/result-app
        