apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    app: result
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: result
  type: LoadBalancer