apiVersion: v1
kind: ReplicationController
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: lukereimer/worker
        