apiVersion: v1
kind: ReplicationController
metadata:
  name: voting
  labels:
    app: voting
spec:
  replicas: 1
  selector:
    app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: voting
        image: lukereimer/voting-app
        